FROM node:17.6.0-alpine as build

WORKDIR /app
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . ./
RUN yarn && yarn build

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /app/build /nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]